# vim:ft=kitty

# TODO: implement kitty-xonsh shell integration

# Font
font_family JetBrainsMono Nerd Font
font_size 14
bold_font auto
italic_font auto
bold_italic_font auto
modify_font cell_height 120% # line height
disable_ligatures cursor

remember_window_size        no
initial_window_width        950
initial_window_height       500

scrollback_lines            5000
confirm_os_window_close     0
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}:{title}"

include colors/Nord.conf
globinclude conf.d/*.conf

## enable_layouts tall fat:bias=70 grid splits stack

map f11 toggle_layout stack
# map kitty_mod+enter launch --cwd=current --location=split
# map ctrl+g kitten hints --type=linenum --linenum-action=tab nvim +{line} {path}

# conflicts with nvim save w/o formatting
map kitty_mod+s
# conflicts with nvim quit w/o saving
map kitty_mod+q
# conflicts with nvim force restart
map kitty_mod+r

# map kitty_mod+enter
map kitty_mod+h
map kitty_mod+j
map kitty_mod+k
map kitty_mod+l

# shell /usr/bin/bash # shell integrations work for bash

# map kitty_mod+z scroll_to_prompt -1
# map kitty_mod+x scroll_to_prompt 1
