-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "3840x2160@59.997", position = "0x1080", scale = 1.5, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "2560x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-2", mode = "3840x2160@59.997", position = "2560x1080", scale = 1.5, vrr = 0 })
hl.monitor({ output = "DP-3", mode = "1920x1080@60.000", position = "640x0", scale = 1, vrr = 0 })
