# kitty-scrollback.nvim https://github.com/mikesmithgh/kitty-scrollback.nvim

allow_remote_control        yes
listen_on                   unix:/tmp/kitty
shell_integration           enabled

# kitty-scrollback.nvim Kitten alias
# action_alias kitty_scrollback_nvim kitten /home/kjm/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
# Browse scrollback buffer in nvim
# map kitty_mod+space kitty_scrollback_nvim
# Browse output of the last shell command in nvim
# map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
# mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output


# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' --cmd 'set eventignore=FileType' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' +'lua vim.fn.winrestview({topline=41})' +'set number' +'lua vim.print({topline=INPUT_LINE_NUMBER,lnum=CURSOR_LINE,col=CURSOR_COLUMN})' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' +'lua vim.api.nvim_win_set_cursor(0,{CURSOR_LINE, CURSOR_COLUMN})' +'set number' +'lua vim.print({topline=INPUT_LINE_NUMBER,lnum=CURSOR_LINE,col=CURSOR_COLUMN})' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' +'lua vim.fn.winrestview({topline=INPUT_LINE_NUMBER,lnum=CURSOR_LINE,col=CURSOR_COLUMN-2})' +'lua vim.notify("CURSOR_COLUMN")' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' +'lua vim.api.nvim_win_set_cursor(0,{CURSOR_LINE, CURSOR_COLUMN})' +'set number' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' +'lua vim.fn.winrestview({topline=41,lnum=55,col=3})' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'set number' +INPUT_LINE_NUMBER -c 'normal zt' +CURSOR_LINE +'lua Snacks.terminal.colorize()' -
# scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'set number' +INPUT_LINE_NUMBER -c 'normal zt' +CURSOR_LINE -
scrollback_pager nvim --cmd 'lua vim.g.minimal=true' +'lua Snacks.terminal.colorize()' -

map kitty_mod+space show_scrollback
