#!/usr/bin/env bash

LOCKFILE="${XDG_RUNTIME_DIR:-/tmp}/active-window-info.lock"

# 1. Open the lock file on FD 200
exec 200>"$LOCKFILE"

# 2. Try to acquire the lock. If it fails, FD 200 is still open, but the script exits
flock -n 200 || \
  { notify-send -i dialog-error \
    "Active Window Info" \
    "Program is already running!"; \
    exit 1; 
  }

# --- LOCKED SECTION START ---
datafile=$(mktemp /tmp/activewindow.XXXXXX)

notify-send "Active Window Info" "Pick a window..."

niri msg pick-window > "$datafile"
# --- LOCKED SECTION END ---

# 3. RELEASE THE LOCK manually by closing the file descriptor
exec 200>&-

# 4. Exit if no window is selected
line_count=$(wc -l < "$datafile")
if [[ $line_count -le 1 ]]; then
  notify-send -i dialog-warning \
    "Active Window Info" \
    "$(cat "$datafile")"
  exit 1
fi

# 5. Now launch the terminal
# Another instance of this script can now be started even while this terminal is open.
$TERMINAL --class="active-window-info" -e \
  bash -c "nvim --cmd 'let g:basic=1' '$datafile'; rm -f '$datafile'"
