# ░█░█░█▀█░█░█░█▀▄░█▀█░█▀▄
# ░█▄█░█▀█░░█░░█▀▄░█▀█░█▀▄
# ░▀░▀░▀░▀░░▀░░▀▀░░▀░▀░▀░▀

# Autostart -- instead use systemctl --user enable --now waybar
# exec-once = uwsm-app -- waybar # env GTK_DEBUG=interactive waybar

# Appearance
layerrule = match:namespace waybar, blur on, blur_popups on, ignore_alpha 0

# Keybinds
bindd = SUPER CTRL, B, Reload waybar, exec, systemctl --user restart waybar
# bindd = SUPER CTRL, B, Reload waybar, exec, pkill -x waybar; uwsm-app -- env GTK_DEBUG=interactive waybar
