$image = /home/kjm/wallpapers/swiss-alps.jpg

$background = 16,21,16
$blue = 175,198,255
$blue_container = 45,69,120
$blue_source = 0,0,255
$blue_value = 0,0,255
$cyan = 132,213,196
$cyan_container = 0,80,69
$cyan_source = 0,255,255
$cyan_value = 0,255,255
$error = 255,180,171
$error_container = 147,0,10
$fuchsia = 252,176,213
$fuchsia_container = 108,51,83
$fuchsia_source = 255,0,255
$fuchsia_value = 255,0,255
$green = 160,211,154
$green_container = 35,80,36
$green_source = 0,255,0
$green_value = 0,255,0
$inverse_on_surface = 45,50,44
$inverse_primary = 54,105,62
$inverse_surface = 224,228,219
$on_background = 224,228,219
$on_blue = 20,47,96
$on_blue_container = 217,226,255
$on_cyan = 0,56,47
$on_cyan_container = 159,242,224
$on_error = 105,0,5
$on_error_container = 255,218,214
$on_fuchsia = 82,29,60
$on_fuchsia_container = 255,216,232
$on_green = 9,57,16
$on_green_container = 188,240,180
$on_orange = 84,33,5
$on_orange_container = 255,219,205
$on_primary = 0,57,20
$on_primary_container = 183,241,186
$on_primary_fixed = 0,33,8
$on_primary_fixed_variant = 29,81,40
$on_red = 84,33,5
$on_red_container = 255,219,205
$on_secondary = 36,52,37
$on_secondary_container = 212,232,209
$on_secondary_fixed = 15,31,17
$on_secondary_fixed_variant = 58,75,58
$on_surface = 224,228,219
$on_surface_variant = 193,201,190
$on_tertiary = 0,54,61
$on_tertiary_container = 189,234,243
$on_tertiary_fixed = 0,31,36
$on_tertiary_fixed_variant = 31,77,84
$on_yellow = 38,53,0
$on_yellow_container = 212,236,157
$orange = 255,181,149
$orange_container = 113,54,25
$orange_source = 255,0,0
$orange_value = 255,0,0
$outline = 139,147,137
$outline_variant = 66,73,64
$primary = 156,212,159
$primary_container = 29,81,40
$primary_fixed = 183,241,186
$primary_fixed_dim = 156,212,159
$red = 255,181,149
$red_container = 113,54,25
$red_source = 255,0,0
$red_value = 255,0,0
$scrim = 0,0,0
$secondary = 184,204,182
$secondary_container = 58,75,58
$secondary_fixed = 212,232,209
$secondary_fixed_dim = 184,204,182
$shadow = 0,0,0
$source_color = 5,15,6
$surface = 16,21,16
$surface_bright = 54,58,53
$surface_container = 28,33,28
$surface_container_high = 39,43,38
$surface_container_highest = 49,54,48
$surface_container_low = 24,29,24
$surface_container_lowest = 11,15,11
$surface_dim = 16,21,16
$surface_tint = 156,212,159
$surface_variant = 66,73,64
$tertiary = 161,206,215
$tertiary_container = 31,77,84
$tertiary_fixed = 189,234,243
$tertiary_fixed_dim = 161,206,215
$yellow = 184,207,132
$yellow_container = 59,77,15
$yellow_source = 255,255,0
$yellow_value = 255,255,0
