#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Rclone"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm rclone cronie

sudo systemctl enable cronie.service

rclone bisync Proton: ~/Proton --resync >> "$HOME"/.local/share/rclone/logs/Proton.log 2>&1
