#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Superfile"
echo "--------------------------------------------------------------------------------"

yay -S --needed --noconfirm superfile perl-image-exiftool zoxide
