# ░█▄█░█▀█░█░█░█▀█
# ░█░█░█▀█░█▀▄░█░█
# ░▀░▀░▀░▀░▀░▀░▀▀▀

# Autostart -- may need to enable/start systemd service
# exec-once = uwsm-app -- mako

# Appearance
layerrule = match:namespace notifications, blur on, ignore_alpha 0

# Keybinds
bindd = SUPER, N, Dismiss notifications, exec, makoctl dismiss -a
