[services]
  system = [
    "cups",
    "avahi-daemon",
    "udevmon",
    # "sddm",
    # "cosmic-greeter",
  ]
  user = [
    "pipewire",
    "wireplumber",
    "pipewire-pulse",
    "gnome-keyring-daemon",
    # "hypridle",
    "stasis",
    "udiskie",
    "swayosd-server",
    "waybar",
  ]
