#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Waybar"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm waybar

systemctl --user enable waybar
