"$schema" = 'https://starship.rs/config-schema.json'

# add_newline = false
command_timeout = 750

format = """ $all${env_var.yazilevel}"""

# right_format = "$battery$shell$os"

[fill]
  # disabled = true
  symbol = "─"

[line_break]
  disabled = false

[shell]
  disabled             = false
  format               = "$indicator"
  bash_indicator       = "[ ](bright-yellow)"
  fish_indicator       = "[ 󰈺](blue)"
  zsh_indicator        = "[ 󰵁](bright-purple)"
  powershell_indicator = "[ ](cyan)"
  pwsh_indicator       = "[ 󰨊](blue)"
  cmd_indicator        = "[ ](yellow)"
  nu_indicator         = "[ >](#39884d)"
  xonsh_indicator      = "[ 🐚](purple)"
  unknown_indicator    = "[ ](red)"

[username]
  # show_always = true
  format     = '[$user]($style)'
  style_user = 'yellow'

[hostname]
  # ssh_only   = false
  format     = "[@($ssh_symbol )$hostname]($style) "
  ssh_symbol = '🌏'
  # detect_env_vars = ['SSH_TTY', 'SSH_CONNECTION', 'SSH_CLIENT']

  # [localip]
  # disabled = false
  # ssh_only = false

[directory]
  truncation_length = 7
  # truncate_to_repo = false
  # style = "bg:bright-black fg:cyan inverted"
  repo_root_style = "bold"
  read_only = " "
  read_only_style = "red"
  style = "cyan"
  format = """\
[$read_only]($read_only_style)\
[$path]($style) \
"""
  repo_root_format = """\
[$read_only]($read_only_style)\
[$before_root_path]($before_repo_root_style)\
[ $repo_root]($style $repo_root_style)\
[$path]($style) \
"""
  use_logical_path = false
  # fish_style_pwd_dir_length = 1

  # [directory.substitutions]
  #   '/mnt/NAS' = '󱛟 '
  #   library    = '📚'
  #   books      = '📖'
  #   software   = '💾'

[git_branch]
  symbol = "󰘬 "
  format = """[$symbol$branch(:$remote_branch)]($style) """
  style  = "purple"

[git_commit]
  format = '[\($hash$tag\)]($style) '
  style  = "#646A76"

[git_status]
  format           = "[$all_status$ahead_behind]($style)"
  style            = "default"
  windows_starship = "/mnt/c/Users/McNamaraK/scoop/shims/starship.exe" # NOTE: may need to change
  conflicted       = "[‼$count](red) "                                 # =
  stashed          = "[ $count](white) "                              # \\$
  deleted          = "[󰆴$count](bold red) "                            # ✘
  renamed          = "[ $count](bold yellow) "                        # »
  modified         = "[ $count](yellow) "                             # !
  staged           = "[ $count](green) "                              # +
  untracked        = "[ $count](bold black) "                         # ?
  diverged         = "⇕$ahead_count/$behind_count "
  ahead            = "[⇡$count](blue) "
  behind           = "[⇣$count](bold blue) "

[package]
  disabled = true
  format   = "[$symbol$version]($style) "
  style    = "bold yellow"

[lua]
  disabled = true

[python]
  symbol = " "
  style  = "blue"
  format = '[$symbol$pyenv_prefix($version )(\($virtualenv\) )]($style)'

[nodejs]
  format = '[$symbol($version)]($style) '

[os]
  disabled = true

  [os.symbols]
    Windows          = "󰍲 "
    Ubuntu           = "󰕈 "
    SUSE             = " "
    Raspbian         = "󰐿 "
    Mint             = "󰣭 "
    Macos            = "󰀵 "
    Manjaro          = " "
    Linux            = "󰌽 "
    Gentoo           = "󰣨 "
    Fedora           = "󰣛 "
    Alpine           = " "
    Amazon           = " "
    Android          = " "
    Arch             = "󰣇 "
    Artix            = "󰣇 "
    CentOS           = " "
    Debian           = "󰣚 "
    Redhat           = "󱄛 "
    RedHatEnterprise = "󱄛 "

[cmd_duration]
  # disabled           = true
  style  = "bold yellow"
  format = "[($duration )]($style) "
  # show_notifications = true

[character]
  # disabled = true
  success_symbol            = '[ ❯](green)'
  error_symbol              = '[ ❯](red)'
  vimcmd_symbol             = '[ ❮](cyan)'
  vimcmd_replace_one_symbol = '[ ✘](purple)'
  vimcmd_replace_symbol     = '[ ✘](bold yellow)'
  vimcmd_visual_symbol      = '[ ](yellow)'

[env_var.yazi_level]
  description = "Indicate the shell was launched by `yazi`"
  variable    = "YAZI_LEVEL"
  symbol      = "󰇥"
  format      = '[$symbol ]($style)'
  style       = "yellow"
