-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

require("dms.colors")
require("dms.outputs")
require("dms.workspaces")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

hl.env("TERMINAL", "ghostty")

hl.config({
  input = {
    -- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
    kb_layout = "",
    numlock_by_default = true,
    follow_mouse = 1,
    mouse_refocus = false,
    touchpad = {
      natural_scroll = true,
      tap_to_click = true,
      clickfinger_behavior = true,
    },
  },
  cursor = {
    hide_on_key_press = true,
    persistent_warps = true,
    -- no_warps = true,
  },
  general = {
    border_size = 3,
    gaps_in = 5,
    gaps_out = 10,
    layout = "scrolling",
    no_focus_fallback = true,
    resize_on_border = true,
    snap = { enabled = true },
  },
  decoration = {
    rounding = 12,
    active_opacity = 1.0,
    inactive_opacity = 0.8,
    fullscreen_opacity = 1.0,
    -- dim_special = 0.5,
    blur = {
      enabled = true,
      size = 20,
      passes = 3,
      popups = true,
    },
    shadow = {
      enabled = true,
      range = 30,
      render_power = 3,
      offset = { 0, 5 },
      color = "rgba(00000070)",
    },
  },
  group = {
    groupbar = {
      font_size = 14,
      font_weight_active = "bold",
      indicator_height = 8,
      rounding = 4,
      round_only_edges = false,
      gradient_rounding = 10,
      gaps_in = 10,
      gaps_out = 5,
    },
  },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    font_family = "JetBrainsMono Nerd Font",
    animate_manual_resizes = true,
    focus_on_activate = true,
    allow_session_lock_restore = true,
  },
  ecosystem = {
    no_update_news = true,
  },
  dwindle = {
    preserve_split = true,
  },
  master = {
    mfact = 0.5,
  },
  scrolling = {
    wrap_focus = false,
    wrap_swapcol = false,
  },
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default", style = "slidevert" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
  match = { class = "^(steam)$", title = "^(notificationtoasts)" },
  no_initial_focus = true,
  pin = true,
})
hl.window_rule({
  match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
  float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })
