#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Hyprland"
echo "--------------------------------------------------------------------------------"

packages=(
  hyprland
  hyprlock
  hyprpaper
  xdg-desktop-portal-hyprland
  polkit-gnome
  qt5-wayland
  qt6-wayland
  hyprcursor
  nordzy-hyprcursors
  nordzy-cursors
  udiskie
  hyprpaper
  waypaper
  hyprpicker
  hyprlock
  dunst
  rofi-wayland
  cliphist
  waybar
  wlogout
  python-pywal
  nm-connection-editor
  network-manager-applet
  blueberry-wayland
)

yay -S --noconfirm "${packages[@]}"

# echo
# echo "--------------------------------------------------------------------------------"
# echo "*** Hyprland Plugin Manager"
# echo "--------------------------------------------------------------------------------"

# yay -S --noconfirm hyprland
# yay -S --noconfirm cmake
# yay -S --noconfirm meson
# yay -S --noconfirm cpio

# hyprpm add https://github.com/hyprwm/hyprland-plugins
# hyprpm add https://github.com/outfoxxed/hy3
# hyprpm update
# hyprpm enable hyprexpo
# hyprpm enable hy3
# hyprpm reload
