#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Hyprland"
echo "--------------------------------------------------------------------------------"

packages=(
  uwsm
  hyprland
  hyprpaper
  hyprlock
  hypridle
  hyprcursor
  hyprpicker
  cliphist
  xdg-desktop-portal-hyprland
  polkit-gnome
  # blueberry-wayland
  brightnessctl
  # qt5-wayland
  # qt6-wayland
  pyprland
  udiskie
  # dunst
  # wlogout
  # nm-connection-editor
  # network-manager-applet

  # theming
  nordzy-hyprcursors
  nordzy-cursors
  adw-gtk-theme
  papirus-icon-theme
)

yay -S --needed --noconfirm "${packages[@]}"

# echo
# echo "--------------------------------------------------------------------------------"
# echo "*** Hyprland Plugin Manager"
# echo "--------------------------------------------------------------------------------"

# yay -S --noconfirm hyprland
# yay -S --noconfirm cmake
# yay -S --noconfirm meson
# yay -S --noconfirm cpio

# hyprpm add https://github.com/hyprwm/hyprland-plugins
# hyprpm add https://github.com/outfoxxed/hy3
# hyprpm update
# hyprpm enable hyprexpo
# hyprpm enable hy3
# hyprpm reload
