#!/usr/bin/env bash

if command -v wiremix &> /dev/null; then
  pkill -x wiremix || exec setsid uwsm-app -- "$TUI_TERMINAL" --class=wiremix -e wiremix "$@"
else
  notify-send -u critical "Audio tool (wiremix) not installed!"
fi
