[[plugin.deps]]
use = "boydaihungst/mediainfo"
rev = "f1cec0b"
hash = "fd9312e974c63438b1f8737711462d52"

[[plugin.deps]]
use = "ndtoan96/ouch"
rev = "596b666"
hash = "c2f4f4aca257dcceafa9e3b828dbf1c9"

[[plugin.deps]]
use = "yazi-rs/plugins:chmod"
rev = "f703392"
hash = "87472b05a8c420100f6a2b9cde1e7746"

[[plugin.deps]]
use = "yazi-rs/plugins:full-border"
rev = "f703392"
hash = "f281261ff04ad7ec867c3f802a50835f"

[[plugin.deps]]
use = "yazi-rs/plugins:git"
rev = "f703392"
hash = "347cc6b190eb0c2fd60513cc7ae37412"

[[plugin.deps]]
use = "yazi-rs/plugins:toggle-pane"
rev = "f703392"
hash = "5b2fbef7d1513ce38ff72623a071a5e"

[[plugin.deps]]
use = "alberti42/faster-piper"
rev = "bb90261"
hash = "12b5e342d54db42b5b023faa1a11f28e"

[flavor]
deps = []
