#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Walker (Launcher)"
echo "--------------------------------------------------------------------------------"

packages=(
  walker-bin
  elephant-bin
  elephant-calc-bin
  elephant-todo-bin
  elephant-files-bin
  elephant-menus-bin
  elephant-runner-bin
  elephant-symbols-bin
  elephant-snippets-bin
  elephant-unicode-bin
  elephant-bluetooth-bin
  elephant-clipboard-bin
  elephant-websearch-bin
  elephant-providerlist-bin
  elephant-archlinuxpkgs-bin
  elephant-desktopapplications-bin
)
yay -S --needed --noconfirm "${packages[@]}"
