#!/usr/bin/env bash

host="$1"
dotfiles="/root/dotfiles"
config="$dotfiles/arch/$host.json"
users="$dotfiles/arch/users.json"
archmount="/mnt/archinstall"

pacman -Sy
pacman -S --needed --noconfirm git

git clone --branch "$host" git@github.com:kjmcnamara1/dotfiles "$dotfiles"

username=$(cat "$users" | jq -r '.users[0].username')

archinstall --config "$config" --creds "$users"

cp -r "$dotfiles/arch/etc" "$archmount"

read -rp "Press enter to continue..."

arch-chroot "$archmount" bash -c "sudo -H -u $username chezmoi init --apply kjmcnamara1"

read -rp "Press enter to continue..."

# Disable default action of power button
sed -i 's/.*HandlePowerKey=.*/HandlePowerKey=ignore/' "$archmount/etc/systemd/logind.conf"
# Add mDNS for printer
sed -i 's/mymachines resolve/mymachines mdns_minimal [NOTFOUND=return] resolve/' "$archmount/etc/nsswitch.conf"
# Add NAS mount to fstab
grep -q "192.168.0.10:/mnt/md1" /etc/fstab || echo "\n# /mnt/NAS\n192.168.0.10:/mnt/md1 /mnt/NAS nfs defaults 0 0" >> /etc/fstab

# Idempotently add 'quiet splash' to all boot entries
for entry in "$archmount"/boot/loader/entries/*.conf; do
  sudo sed -i '/^options / { s/ quiet//g; s/ splash//g; s/$/ quiet splash/ }' "$entry"
done
# Add plymouth to mkinitcpio hooks after 'base udev'
# it will only add 'plymouth' if it is not already present
sed -i '/^HOOKS=/!b; /plymouth/!s/\(base udev\)/\1 plymouth/' "$archmount/etc/mkinitcpio.conf"
# Change theme and regenerate initramfs
arch-chroot "$archmount" plymouth-set-default-theme -R arch-charge-big
# Write systemd-boot config (Should also change the EFI variable)
bootctl --esp-path="$archmount/boot" --boot-path="$archmount/boot" set-timeout "0"

# TODO: plymouth theme and quiet boot

# reboot
