#!/usr/bin/env bash

# Set default values
DEFAULT_CONFIG_NAME=muse
DEFAULT_USERNAME=kjm

# Get archinstall config name from user
read -rp "Name of config to use [$DEFAULT_CONFIG_NAME]: " config_name
config_name=${config_name:-$DEFAULT_CONFIG_NAME}

# Select config file
config_file="https://raw.githubusercontent.com/kjmcnamara1/dotfiles/refs/heads/main/arch/$config_name.json"
echo "Using config file: $config_file"

# Read credentials from user
echo
read -rp "Username [$DEFAULT_USERNAME]: " username
username=${username:-$DEFAULT_USERNAME}
read -srp "Password: " password

# Save credentials to temp file
cred_file="$(mktemp)"
cat > "$cred_file" << EOF
{
    "!root-password": "$password",
    "!users": [
        {
            "!password": "$password",
            "sudo": true,
            "username": "$username"
        }
    ]
}
EOF

# echo
# echo "$cred_file"
# cat "$cred_file"

archinstall --config "$config_file" --creds "$cred_file" && reboot
