#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** NWG Look"
echo "--------------------------------------------------------------------------------"

packages=(
  nwg-look
  nordzy-cursors
  adw-gtk-theme
  papirus-icon-theme

  # qogir-icon-theme
  # materia-gtk-theme
)

yay -S --needed --noconfirm "${packages[@]}"
