#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Visual Studio Code"
echo "--------------------------------------------------------------------------------"

# yay -S --noconfirm code code-marketplace code-features
yay -S --noconfirm visual-studio-code-bin
