#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Cosmic DE"
echo "--------------------------------------------------------------------------------"

packages=(
  cosmic
  power-profiles-daemon
  wl-clipboard
  loupe    # gnome image viewer
  gwenview # kde image viewer
  kvantum
  qt6-wayland
  qt6ct
)

yay -S --noconfirm "${packages[@]}"
