#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** SwayOSD (On Screen Display)"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm swayosd

systemctl --user enable swayosd-server
