#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Thunar"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm thunar sshfs gvfs gvfs-smb gvfs-nfs gvfs-google gvfs-onedrive gnome-disk-utility
