#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** OnlyOffice"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm onlyoffice-bin

xdg-mime default onlyoffice-desktopeditors.desktop application/pdf
