# vim: ft=config

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bind = NONE, XF86AudioMute        , spawn, ~/.config/swayosd/scripts/osdclient --output-volume mute-toggle
bindl = NONE, XF86AudioLowerVolume , spawn, ~/.config/swayosd/scripts/osdclient --output-volume lower
bindl = NONE, XF86AudioRaiseVolume , spawn, ~/.config/swayosd/scripts/osdclient --output-volume raise
bindl = NONE, XF86AudioMicMute     , spawn, ~/.config/swayosd/scripts/osdclient --input-volume mute-toggle
bindl = NONE, XF86MonBrightnessUp  , spawn, ~/.config/swayosd/scripts/osdclient --brightness raise
bindl = NONE, XF86MonBrightnessDown, spawn, ~/.config/swayosd/scripts/osdclient --brightness lower
# {{ if eq .chezmoi.hostname "angel" }}
bindl = NONE, XF86MonBrightnessUp  , spawn, hyprctl hyprsunset gamma +10
bindl = NONE, XF86MonBrightnessDown, spawn, hyprctl hyprsunset gamma -10
# {{ end }}

# Precise 1% multimedia adjustments with Alt modifier
bindl = ALT, XF86AudioLowerVolume , spawn, ~/.config/swayosd/scripts/osdclient --output-volume -1
bindl = ALT, XF86AudioRaiseVolume , spawn, ~/.config/swayosd/scripts/osdclient --output-volume +1
bindl = ALT, XF86MonBrightnessUp  , spawn, ~/.config/swayosd/scripts/osdclient --brightness +1
bindl = ALT, XF86MonBrightnessDown, spawn, ~/.config/swayosd/scripts/osdclient --brightness -1

# Media control
bindl = NONE, XF86AudioPlay , spawn, ~/.config/swayosd/scripts/osdclient --playerctl play-pause
bindl = NONE, XF86AudioPause, spawn, ~/.config/swayosd/scripts/osdclient --playerctl play-pause
bindl = NONE, XF86AudioNext , spawn, ~/.config/swayosd/scripts/osdclient --playerctl next
bindl = NONE, XF86AudioPrev , spawn, ~/.config/swayosd/scripts/osdclient --playerctl previous

