#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Neovim"
echo "--------------------------------------------------------------------------------"

yay -S --noconfirm neovim nodejs npm chafa imagemagick
