#! /usr/bin/env bash

echo
echo "--------------------------------------------------------------------------------"
echo "*** Sway"
echo "--------------------------------------------------------------------------------"

packages=(
  sway
  swaybg
  cliphist
  xdg-desktop-portal-wlr
  polkit-gnome
  blueberry-wayland
)

yay -S --noconfirm "${packages[@]}"
